[
  {
    title: "Professional Plumbing Services",
    description:
      "Expert plumbing services for leak repairs, pipe installations, and maintenance.",
    price: "1500",
    cover: "plumber.jpg",
    category: "Plumber",
    providerid: "USER_ID",
    status: "new",
    location: "Local Area",
    providerEmail: "USER_EMAIL",
    compitionDate: "2025-04-10",
  },
  {
    title: "Carpenter for Custom Furniture & Repairs",
    description:
      "Skilled carpenter available for furniture repair, door fixing, and woodwork.",
    price: "2000",
    cover: "carpenter.jpg",
    category: "Carpenter",
    providerid: "USER_ID",
    status: "new",
    location: "Local Area",
    providerEmail: "USER_EMAIL",
    compitionDate: "2025-04-15",
  },
  {
    title: "Caretaker for Home & Elderly Care",
    description: "Experienced caretaker for elderly and home assistance.",
    price: "1800",
    cover: "caretaker.jpg",
    category: "Caretaker",
    providerid: "USER_ID",
    status: "new",
    location: "Local Area",
    providerEmail: "USER_EMAIL",
    compitionDate: "2025-04-12",
  },
  {
    title: "Labour for Construction & Heavy Work",
    description:
      "Reliable and hardworking labour for construction, loading, and shifting tasks.",
    price: "1200",
    cover: "labour.jpg",
    category: "Labour",
    providerid: "USER_ID",
    status: "new",
    location: "Local Area",
    providerEmail: "USER_EMAIL",
    compitionDate: "2025-04-18",
  },
  {
    title: "Tailoring & Stitching Services",
    description:
      "Professional tailor for custom stitching, alterations, and dressmaking.",
    price: "1300",
    cover: "tailor.jpg",
    category: "Tailor",
    providerid: "USER_ID",
    status: "new",
    location: "Local Area",
    providerEmail: "USER_EMAIL",
    compitionDate: "2025-04-20",
  },
  {
    title: "Electrician for Home & Office Repairs",
    description:
      "Certified electrician for wiring, repairs, and appliance installations.",
    price: "1600",
    cover: "electrician.jpg",
    category: "Electrician",
    providerid: "USER_ID",
    status: "new",
    location: "Local Area",
    providerEmail: "USER_EMAIL",
    compitionDate: "2025-04-25",
  },
  {
    title: "Painter for House & Commercial Spaces",
    description:
      "Experienced painter available for homes, offices, and buildings.",
    price: "1700",
    cover: "painter.jpg",
    category: "Painter",
    providerid: "USER_ID",
    status: "new",
    location: "Local Area",
    providerEmail: "USER_EMAIL",
    compitionDate: "2025-04-30",
  },
  {
    title: "Mechanic for Bike & Car Repairs",
    description:
      "Expert mechanic for car and bike servicing, repairs, and maintenance.",
    price: "2500",
    cover: "mechanic.jpg",
    category: "Mechanic",
    providerid: "USER_ID",
    status: "new",
    location: "Local Area",
    providerEmail: "USER_EMAIL",
    compitionDate: "2025-05-05",
  },
  {
    title: "House Cleaning & Deep Cleaning Services",
    description:
      "Professional cleaning services for homes, offices, and apartments.",
    price: "1400",
    cover: "cleaning.jpg",
    category: "Cleaning",
    providerid: "USER_ID",
    status: "new",
    location: "Local Area",
    providerEmail: "USER_EMAIL",
    compitionDate: "2025-05-08",
  },
  {
    title: "Mason for Construction & Repair Work",
    description: "Skilled mason for brickwork, plastering, and renovations.",
    price: "2000",
    cover: "mason.jpg",
    category: "Mason",
    providerid: "USER_ID",
    status: "new",
    location: "Local Area",
    providerEmail: "USER_EMAIL",
    compitionDate: "2025-05-10",
  },
  {
    title: "Gardening & Lawn Maintenance",
    description:
      "Experienced gardener for plant care, landscaping, and garden maintenance.",
    price: "1500",
    cover: "gardener.jpg",
    category: "Gardener",
    providerid: "USER_ID",
    status: "new",
    location: "Local Area",
    providerEmail: "USER_EMAIL",
    compitionDate: "2025-05-12",
  },
  {
    title: "Security Guard Services",
    description:
      "Trained security guard for home, office, and event protection.",
    price: "2200",
    cover: "security.jpg",
    category: "Security Guard",
    providerid: "USER_ID",
    status: "new",
    location: "Local Area",
    providerEmail: "USER_EMAIL",
    compitionDate: "2025-05-15",
  },
  {
    title: "Catering Services for Events & Parties",
    description:
      "Delicious catering for weddings, birthdays, and corporate events.",
    price: "3000",
    cover: "catering.jpg",
    category: "Catering",
    providerid: "USER_ID",
    status: "new",
    location: "Local Area",
    providerEmail: "USER_EMAIL",
    compitionDate: "2025-05-18",
  },
  {
    title: "Tiffin Services for Home & Office",
    description: "Healthy and homemade meals delivered to your doorstep.",
    price: "1200",
    cover: "tiffin.jpg",
    category: "Tiffin Services",
    providerid: "USER_ID",
    status: "new",
    location: "Local Area",
    providerEmail: "USER_EMAIL",
    compitionDate: "2025-05-20",
  },
  {
    title: "Pest Control Services",
    description: "Affordable and effective pest control for homes and offices.",
    price: "2500",
    cover: "pestcontrol.jpg",
    category: "Pest Control",
    providerid: "USER_ID",
    status: "new",
    location: "Local Area",
    providerEmail: "USER_EMAIL",
    compitionDate: "2025-05-22",
  },
  {
    title: "Movers & Packers Services",
    description:
      "Reliable moving and packing services for shifting homes and offices.",
    price: "5000",
    cover: "movers.jpg",
    category: "Movers & Packers",
    providerid: "USER_ID",
    status: "new",
    location: "Local Area",
    providerEmail: "USER_EMAIL",
    compitionDate: "2025-05-25",
  },
  {
    title: "AC Repair & Installation",
    description:
      "Expert AC repair, servicing, and installation at affordable rates.",
    price: "3000",
    cover: "acrepair.jpg",
    category: "AC Repair",
    providerid: "USER_ID",
    status: "new",
    location: "Local Area",
    providerEmail: "USER_EMAIL",
    compitionDate: "2025-05-28",
  },
];
